# air在运行时存储临时文件的目录
tmp_dir = "/tmp/air"

[build]
# cmd 指定了监听文件有变化时, air需要执行的命令
# 这里指了执行 make build 重新构建ifonly-apiserver二进制文件
cmd = "go build -o _output/ifonly-apiserver -v cmd/ifonly-apiserver/main.go"

# bin指定了执行完cmd命令后，执行的二进制文件
# 这里制定了执行_output/ifonly-apiserver文件
bin = "_output/ifonly-apiserver"

# args_bin 指定了运行二进制文件(bin/full_bin)时添加额外参数，这里设置空，目前不需要
airs_bin = []