// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: apiserver/v1/apiserver.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IfOnly_Healthz_FullMethodName = "/v1.IfOnly/Healthz"
)

// IfOnlyClient is the client API for IfOnly service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IfOnlyClient interface {
	// Healthz健康检查
	Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error)
}

type ifOnlyClient struct {
	cc grpc.ClientConnInterface
}

func NewIfOnlyClient(cc grpc.ClientConnInterface) IfOnlyClient {
	return &ifOnlyClient{cc}
}

func (c *ifOnlyClient) Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, IfOnly_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IfOnlyServer is the server API for IfOnly service.
// All implementations must embed UnimplementedIfOnlyServer
// for forward compatibility.
type IfOnlyServer interface {
	// Healthz健康检查
	Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error)
	mustEmbedUnimplementedIfOnlyServer()
}

// UnimplementedIfOnlyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIfOnlyServer struct{}

func (UnimplementedIfOnlyServer) Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedIfOnlyServer) mustEmbedUnimplementedIfOnlyServer() {}
func (UnimplementedIfOnlyServer) testEmbeddedByValue()                {}

// UnsafeIfOnlyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IfOnlyServer will
// result in compilation errors.
type UnsafeIfOnlyServer interface {
	mustEmbedUnimplementedIfOnlyServer()
}

func RegisterIfOnlyServer(s grpc.ServiceRegistrar, srv IfOnlyServer) {
	// If the following call pancis, it indicates UnimplementedIfOnlyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IfOnly_ServiceDesc, srv)
}

func _IfOnly_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IfOnlyServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IfOnly_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IfOnlyServer).Healthz(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// IfOnly_ServiceDesc is the grpc.ServiceDesc for IfOnly service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IfOnly_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.IfOnly",
	HandlerType: (*IfOnlyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _IfOnly_Healthz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apiserver/v1/apiserver.proto",
}
